### PR TITLE
build: output ES modules

### PR DESCRIPTION
**Pull request by jsejcksn**
Hi @alextompkins:

This change refactors the build output to produce ES module code instead of CommonJS module code.

It also introduces `node:` URI-namespaced imports for internal Node.js packages ([this feature](https://nodejs.org/api/esm.html#node-imports) was backported all the way to Node v`12`).

<details>
<summary>Compare updated build output:</summary>

Lines 11–17 in the original build output:

```js
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.jsxImportSourcePlugin = void 0;
const fs_1 = __importDefault(require("fs"));
```

now become:

```js
import fs from 'node:fs';
```
</details>

References:
- [Modules: ECMAScript modules | Node.js Documentation](https://nodejs.org/api/esm.html)
- [Modules: Packages | Node.js Documentation](https://nodejs.org/api/packages.html)

Note: I tested the build output, but did not re-run the tests.

### CODE REVIEW

**Comment by alextompkins** [comment]
Hi, thanks for the contribution @jsejcksn! What's the motivation for this change? Obviously we're keen to move the ecosystem in the direction of ESM, but the current build output should support importing this plugin via either CJS `require()` or ESM `import` thanks to `"esModuleInterop": true`, right?

**Comment by jsejcksn** [comment]
> Obviously we're keen to move the ecosystem in the direction of ESM

I fully agree.

> but the current build output should support importing this plugin via either CJS `require()` or ESM `import` thanks to `"esModuleInterop": true`, right?

If you want to support CJS, then [targeting both](https://nodejs.org/api/packages.html#dual-commonjses-module-packages) during build (two files, and mapping with package exports) is certainly an option. Is that important to you?

Personal (perhaps unpopular?) opinion: Non-standards have always been bad for interop, and I welcome the demise of CJS. 😅

> What's the motivation for this change?

I needed an ESM version (while working on a project which created an ESM bundle _using_ `esbuild` (from within an ESM TypeScript project) which was then used to create other ESM bundles).

I was getting errors from the `require` syntax in your build, so I ended up just copying the [source file](https://github.com/alextompkins/esbuild-plugin-jsximportsource/blob/v0.0.4/src/index.ts) as a local module in my project and modifying the `"fs"` import specifier to `"node:fs"` (in order to match my `"node:*"` [external](https://esbuild.github.io/api/#external) condition).

**Comment by alextompkins** [comment]
> I was getting errors from the require syntax in your build, so I ended up just copying the [source file](https://github.com/alextompkins/esbuild-plugin-jsximportsource/blob/v0.0.4/src/index.ts) as a local module in my project and modifying the "fs" import specifier to "node:fs" (in order to match my "node:*" [external](https://esbuild.github.io/api/#external) condition).

Ah I understand now. Looks like I was wrong about this working for both ESM and CJS consumers. 

> Personal (perhaps unpopular?) opinion: Non-standards have always been bad for interop, and I welcome the demise of CJS. 😅

Amen 🙏 I've been burned by CJS/ESM interop more times than I can count. Unfortunately I actually created this plugin specifically to use in a project which (out of my control) has a CJS esbuild script. I see two approaches we could take:

1. Set up two build targets for ESM & CJS and map them via the `exports` field like you've suggested. 
2. Accept this breaking change and bump the major version of the package. Then CJS consumers can continue to depend on `^0` while ESM consumers use `^1`. 

I think I actually prefer the latter option as it pushes the ecosystem forward and keeps the codebase simple. I doubt I'll make many significant changes to this package in future, but I'll keep a `cjs` branch around in case I need to patch it.

**Review by alextompkins — APPROVED** [review]
Approved, I'll merge and release a new major.

**Comment by alextompkins** [comment]
Please let me know if [v1.0.0](https://github.com/alextompkins/esbuild-plugin-jsximportsource/releases/tag/v1.0.0) works properly for you 😄

**Comment by jsejcksn** [comment]
> Please let me know if [v1.0.0](https://github.com/alextompkins/esbuild-plugin-jsximportsource/releases/tag/v1.0.0) works properly for you 😄

@alextompkins Confirmed: I just
- installed the new release
- replaced the local specifier of the edited module (that I described at the end of [this comment](https://github.com/alextompkins/esbuild-plugin-jsximportsource/pull/3#issuecomment-1186073160)) with the name of this package
- added it as an [external](https://esbuild.github.io/api/#external) dependency

and everything builds the same in my CI/CD.

**Pull request merged**
